### ISSUE TITLE
Unknown function error when opening vim

### ISSUE THREAD

**Issue by hoschi** [machakann/vim-textobj-functioncall#2]
Hi,

I got this error after installation via pathogen :
```
Fehler beim Ausführen von "/home/hoschi/dotfiles/.vim/bundle/vim-textobj-functioncall/plugin/textobj/functioncall.vim":
Zeile   27:
E117: Unbekannte Funktion: textobj#user#plugin
Betätigen Sie die EINGABETASTE oder geben Sie einen Befehl ein
```

Translation:
```
Error executing " /home/hoschi/dotfiles/.vim/bundle/vim-textobj-functioncall/plugin/textobj/functioncall.vim " :
Line 27:
E117 : Unknown function : textobj#user#plugin
Press ENTER or type a command
```

**Comment by machakann** [comment]
Hello, it is because this plugin has been dependent on textobj-user (https://github.com/kana/vim-textobj-user). Actually it is very useful utility when we make own textobject plugin, but I changed my mind.

Now I pushed a commit to independent from it. Please try.

**Comment by hoschi** [comment]
I tried it with latest version `7579a22`, now I don't get any error ... but it doesn't seem to work either. `if` brings me straight into insert mode and inserts the character 'f' into the buffer.

**Comment by machakann** [comment]
Excuse me. I just want to confirm that did you try `vif` or `dif` to select or cut a function-call-like region? Because This is a textobject plugin, so it needs to be used in combination with visual mode or operators.

If it still does not work, could you please tell me the output of a command `:verbose xmap if`?

**Comment by hoschi** [comment]
Sorry, you are right `if` makes no sense. But `vif` or `dif` doesn't work either. Here is my test.js file:
```
var foo = function (x) {
	return x;
};

var bar = {
	method:function (y) {
		return y;
	}
};
```
When the cursor is on one of the `return` statements in normal mode and pressing either `dif` or `vif` it does nothing. Here is the output of `:verbose xmap if`:
```
x  if            <Plug>(textobj-functioncall-i)
        last set by ~/dotfiles/.vim/bundle/vim-textobj-functioncall/plugin/textobj/functioncall.vim
```

**Comment by machakann** [comment]
FYI, https://github.com/kana/vim-textobj-function.
This plugin works on function definition :)

**Comment by hoschi** [comment]
Thanks for the info :)
