### ISSUE TITLE
not working with vim and go ...

### ISSUE THREAD

**Issue by ayoubelmhamdi** [machakann/vim-textobj-functioncall#3]
this plugin does not select anything
this is [my mini fie](https://gist.github.com/ayoubelmhamdi/96ff867e9d04a90a733ebff97ce50b0a#file-mini-lua)

**Comment by machakann** [comment]
It would be helpful if there were more information; a minimum text you tried, the cursor position, what you typed, and filetype.

**Comment by ayoubelmhamdi** [comment]
I test for java and the go ... but I think it works for vim call only
